//ALERT
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
//Authentication
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
//USERS
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCES";
export const ALL_USERS_ERROR = "ALL_USERS_ERROR";
export const GET_USER = "GET_USER";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const EDIT_SUCCESS = "EDIT_SUCCESS";
export const EDIT_ERROR = "EDIT_ERROR";
export const CHANGE_PASS_SUCCESS = "CHANGE_PASS_SUCCESS";
export const CHANGE_PASS_ERROR = "CHANGE_PASS_ERROR ";
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_ERROR = "DELETE_ACCOUNT_ERROR";
export const GET_AVATAR_SUCCESS = "GET_AVATAR_SUCCESS";
export const GET_AVATAR_ERROR = "GET_AVATAR_ERROR";

//GROUPS
export const GROUP_CREATED_SUCCESS = "GROUP_CREATED_SUCCESS";
export const GROUP_CREATED_ERROR = "GROUP_CREATED_ERROR";
export const GET_ALL_GROUPS = "GET_ALL_GROUPS";
export const GET_ALL_GROUPS_ERROR = "GET_ALL_GROUPS_ERROR";
export const GROUP_DELETE_SECCESS = "GROUP_DELETE_SECCESS";
export const GROUP_DELETE_ERROR = "GROUP_DELETE_ERROR";
export const GROUP_PROFILE_SUCCESS = "GROUP_PROFILE_SUCCESS";
export const GROUP_PROFILE_ERROR = "GROUP_PROFILE_ERROR";
export const GROUPS_MEMBERS_SUCCESS = "GROUP_MEMBERS_SUCCESS";
export const GROUPS_MEMBERS_ERROR = "GROUP_MEMBERS_ERROR";
export const ADD_MEMBER_SUCCESS = "ADD MEMBER SUCCESS";
export const ADD_MEMBER_ERROR = "ADD MEMBER ERROR";
export const EDIT_GROUP_SUCCESS = "EDIT_GROUP_SUCCESS";
export const EDIT_GROUP_ERROR = "EDIT_GROUP_ERROR";
export const REMOVE_MEMBER_SUCCESS = "REMOVE_MEMBER_SUCCESS";
export const REMOVE_MEMBER_ERROR = "REMOVE_MEMBER_ERROR";
export const CLEAR_CURRENT_GROUP = "CLEAR_CURRENT_GROUP";
//BLOGS
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_ERROR = "CREATE_BLOG_ERROR";
export const GET_USERS_BLOGS_SUCCESS = "GET_USERS_BLOGS_SUCCESS";
export const GET_USERS_BLOGS_ERROR = "GET_USERS_BLOGS_ERROR";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_ERROR = "GET_POST_ERROR";
export const EDIT_BLOG_SUCCESS = "EDIT_BLOG_SUCCESS";
export const EDIT_BLOG_ERROR = "EDIT_BLOG_ERROR";
export const CLEAR_CURRENT_BLOG = "CLEAR_CURRENT_BLOG";

//REACTIONS
export const SET_REACTION_SUCCESS = "SET_REACTION_SUCCESS";
export const SET_REACTION_ERROR = "SET_REACTION_ERROR";
export const GET_CURRENT_USER_REACTION_SUCCESS =
  "GET_CURRENT_USER_REACTION_SUCCESS";
export const GET_CURRENT_USER_REACTION_ERROR =
  "GET_CURRENT_USER_REACTION_ERROR";
export const CLEAR_CURRENT_REACTION = "CLEAR_CURRENT_REACTION";
export const DELETE_REACTION_SUCCESS = "DELETE_REACTION_SUCCESS";
export const DELETE_REACTION_ERROR = "DELETE_REACTION_ERROR";
export const GET_REACTIONS_SUCCESS = "GET_REACTIONS_SUCCESS";
export const GET_REACTIONS_ERROR = "GET_REACTIONS_ERROR";
export const NUM_OF_REACTIONS_SUCCESS = "NUM_OF_REACTIONS_SUCCESS";
export const NUM_OF_REACTIONS_ERROR = "NUM_OF_REACTIONS_ERROR";
export const CLEAR_REACTIONS = "CLEAR_REACTIONS";

//COMMENTS
export const CREATE_COMMENT_SUCCESS = "CREATE_CONNEMT_SUCCESS";
export const CREATE_COMMENT_ERROR = "CREATE_CONNEMT_ERROR";
export const GET_ALL_COMMENTS_SUCCESS = "GET_ALL_COMMENTS_SUCCESS";
export const GET_ALL_COMMENTS_ERROR = "GET_ALL_COMMENTS_ERROR";
export const CLEAR_CURRENT_COMMENTS = "CLEAR_CURRENT_COMMENTS";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const EDIT_COMMENT_ERROR = "EDIT_COMMENT_ERROR";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";

//NOTIFICATIONS
export const GET_NOTIFY_SUCCESS = "GET_NOTIFY_SUCCESS";
export const GET_NOTIFY_ERROR = "GET_NOTIFY_ERROR";
export const SET_VIEWED_TRUE = "SET_VIEWED_TRUE";
export const SET_SETTINGS_SUCCESS = "SET_SETTINGS_SUCCESS";
export const SET_SETTINGS_ERROR = "SET_SETTINGS_ERROR";
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
export const GET_SETTINGS_ERROR = "GET_SETTINGS_ERROR";
export const CLEAR_NOTIFY = "CLEAR_NOTIFY";

//MESSAGES
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_ERROR = "SEND_MESSAGE_ERROR";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_ERROR = "GET_MESSAGES_ERROR";
export const RECENT_CONVERSATION_SUCCESS = "RECENT_CONVERSATION_SUCCESS";
export const RECENT_CONVERSATION_ERROR = "RECENT_CONVERSATION_ERROR";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const GET_UNREAD_MSG_SUCCESS = "GET_UNREAD_MSG_SUCCESS";
export const GET_UNREAD_MSG_ERROR = "GET_UNREAD_MSG_ERROR";
export const GET_UNREAD_MSG_PER_PERSON_SUCCESS =
  "GET_UNREAD_MSG_PER_PERSON_SUCCESS";
export const GET_UNREAD_MSG_PER_PERSON_ERROR =
  "GET_UNREAD_MSG_PER_PERSON_ERROR";
export const CLEAR_UNREAD = "CLEAR_UNREAD";
export const BLOCK_USER_SUCCESS = "BLOCK_USER_SUCCESS";
export const BLOCK_USER_ERROR = "BLOCK_USER_ERROR";
export const UNBLOCK_USER_SUCCESS = "UNBLOCK_USER_SUCCESS";
export const UNBLOCK_USER_ERROR = "UNBLOCK_USER_ERROR";
export const GET_BLOCKED_USERS_SUCCESS = "GET_BLOCKED_USERS_SUCCESS";
export const GET_BLOCKED_USERS_ERROR = "GET_BLOCKED_USERS_ERROR";

//PHOTOS
export const UPLOAD_PHOTO_SUCCESS = "UPLOAD_PHOTO_SUCCESS";
export const UPLOAD_PHOTO_ERROR = "UPLOAD_PHOTO_ERROR";
